jaffle_shop:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_POSTGRES_PW') }}"
      dbname: jaffle_shop
      schema: dbt_alice

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev

dbt_postgres:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_SNOWFLAKE_PW') }}"
      dbname: dbt_postgres
      schema: demo

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev

dbt_postgres:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_SNOWFLAKE_PW') }}"
      dbname: dbtpostgres
      schema: demo

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev
